### ISSUE TITLE
Italics after comment

### ISSUE THREAD

**Issue by larsenwork** [thibmaek/Sass-Syntax-Highlight#1]
So after a comment the next line is also italics when it shouldn't be:

![screen shot 2015-06-13 at 12 09 41](https://cloud.githubusercontent.com/assets/3859425/8143938/4eb51d0c-11c6-11e5-9333-6584c769b5b8.png)

**Comment by thibmaek** [comment]
Can't seem to reproduce here, sure it's not your syntax color theme?
I didn't change vital code when I forked it over, so issue should already been present in original fork.

![screen shot 2015-06-13 at 12 21 55](https://cloud.githubusercontent.com/assets/6213695/8143954/d4be06ca-11c6-11e5-9d5b-7f372fb56872.png)

**Comment by larsenwork** [comment]
Had the issue before but didn't post since it seemed inactive. It looks like we're using the same theme (One Dark).
Using /* Comments */ works as expected:
![screen shot 2015-06-13 at 12 28 19](https://cloud.githubusercontent.com/assets/3859425/8143976/db717cb2-11c7-11e5-94e5-2e625a60fae5.png)

**Comment by larsenwork** [comment]
Not sure why you closed it but I just checked and the issue is gone so :ok_hand: :+1:

**Comment by thibmaek** [comment]
Closed because I wasnt able to reproduce and seemed more like a bug on your setup than the package itself. Glad it works now.
